// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'img-processing-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import ImgProcessing from 'img-processing';

export const metadata: Metadata = {
  resource: 'images',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/v1/images/imagine',
  operationId: 'generateImage',
};

export const tool: Tool = {
  name: 'imagine_images',
  description:
    'The imagine endpoint allows you to create a new image using AI. At the moment, there is support for the models: ByteDance SDXL-Lightning and Flux, which generates good quality images from text descriptions.\n\nThe images generated by the endpoint has a resolution of 1024x1024 pixels and are saved in JPEG format.',
  inputSchema: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
        description: 'The name of the image to identify it on the dashboard.',
      },
      prompt: {
        type: 'string',
        description:
          'The prompt for the image. It should describe what you want to see in the generated image.',
      },
      model: {
        type: 'string',
        description: 'The model to use for the image. If not provided, the default model will be used.',
        enum: ['sdxl', 'flux'],
      },
      negative_prompt: {
        type: 'string',
        description:
          "The negative prompt for the image. It should describe what you don't want to see in the generated image.",
      },
      seed: {
        type: 'integer',
        description:
          'The seed for the image. It is used to generate the image. If not provided, a random seed will be used.',
      },
    },
  },
};

export const handler = async (client: ImgProcessing, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return asTextContentResult(await client.images.imagine(body));
};

export default { metadata, tool, handler };
